### ISSUE TITLE
第六章第五节的习题 IntersectWith 函数实现的有错误！

### ISSUE THREAD

**Issue by xavierskip** [shun-y0k0ta19/gopl#1]
https://github.com/y0k0ta19/gopl/blob/master/CH06/ex03/intsetEx3.go#L50

t.words 的长度比 s.words 长度的话，会引发 error: index out of range 的错误。

**Comment by shun-y0k0ta19** [comment]
thank you for your poiting them out.
fixed this issue.
https://github.com/y0k0ta19/gopl/commit/6ba7400dfb701e3ecc987dbb247c48aca5ef8824
